name: inglo
description: "2024 solution challenge inglo"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

#모바일에 표시될 앱이름
flutter_launcher_name:
  name: "inglo"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.15.3
  firebase_storage: ^11.6.4
  firebase_messaging: ^14.7.15
# 2024 2 3 기준 version
  cupertino_icons: ^1.0.2
  carousel_slider:
  flutter_svg: ^2.0.9 # svg icon으로 사용
  flutter_svg_provider: ^1.0.7 # svg backgorund image로 사용

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/navigation/
    - assets/image/background/
    - assets/image/
